d<-read.csv("~/Downloads/data4a.csv")
d<-read.csv("~/Desktop/programing/midoribon/kubobook2012/chapter06/binomial/data4b.csv")
fit.xf=glm(y~x, offset=log(A), family=poisson, data=d)
d<-read.csv("~/Downloads/practice.csv")
logistic<-function(z) 1/(1+exp(-z))
z<-seq(-6, 6, 0.1)
plot(z, logistic(z))
glm(cbind(Dead,Living)~Dosage,data=d,family=binomial)
exp(6.403*0.10)
